name: Sync Preproduccion to Produccion

on:
  push:
    branches:
      - main
    # O puedes usar cualquier otra rama en 'preproduccion' que desees.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Preproduccion repository
      uses: actions/checkout@v3

    - name: Push to Produccion
      run: |
        git remote add produccion git@github.com:MonlauAlumni/produccion.git
        git push --force produccion main
