name: Deploy to Production

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar acceso a repo de producción
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add production https://x-access-token:${{ secrets.PROD_GIT_TOKEN }}@github.com/MonlauAlumni/produccion.git
          git fetch produccion

      - name: Merge master (pre) → main (prod)
        run: |
          git checkout main
          git merge origin/master --no-edit
          git push production main
