name: Deploy to Production

on:
  push:
    branches:
      - main  # El evento se activa al hacer un push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos Ubuntu como entorno de ejecución

    steps:
    # Paso 1: Configuración del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configuración de SSH (si es necesario)
    - name: Set up SSH key for Git
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Paso 3: Hacer fetch y merge (si es necesario)
    - name: Fetch and merge changes
      run: |
        git fetch origin
        git checkout main
        git merge origin/main || echo "No merge required" # Si no hay conflicto, sigue adelante

    - name: Push to production
      run: |
        git remote add produccion git@github.com:MonlauAlumni/produccion.git
        git push produccion main
