name: Deploy to Production

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Limpiar caché de Git
        run: |
          rm -rf .git

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Debug SSH
        run: |
          ls -la ~/.ssh
          ssh -T git@github.com || echo "Error de autenticación SSH"

      - name: Configurar acceso a repo de producción
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote remove produccion || echo "No se encontró remoto 'produccion'"
          git remote add produccion git@github.com:MonlauAlumni/produccion.git

      - name: Deshabilitar compresión de Git
        run: |
          git config --global core.compression 0

      - name: Verificar y limpiar objetos Git
        run: |
          git fsck --full || echo "No se encontraron problemas"

      - name: Clonación parcial (con --depth 1) y fetch completo
        run: |
          git fetch --depth=1 produccion
          git fetch --unshallow produccion || echo "Error al hacer fetch del repositorio completo"

      - name: Resetear main (prod) a master (pre) (OPCIÓN LIMPIA)
        run: |
          git fetch produccion
          git checkout main
          git reset --hard origin/master
          git push produccion main --force-with-lease

      # Alternativa con merge (si prefieres mantener historial)
      # - name: Merge master (pre) → main (prod)
      #   run: |
      #     git fetch produccion
      #     git checkout main
      #     git merge origin/master --no-ff --no-edit --allow-unrelated-histories || echo "Error al hacer merge"
      #     git push produccion main || echo "Error al hacer push"
