name: Deploy to Production

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar token
        run: echo "${{ secrets.PROD_GIT_TOKEN }}"

      - name: Configurar acceso a repo de producción
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add produccion https://x-access-token:${{ secrets.PROD_GIT_TOKEN }}@github.com/MonlauAlumni/produccion.git

          git fetch produccion || echo "No se pudo hacer fetch de produccion"

      - name: Verificar configuración de Git (Debug)
        run: |
          git config --list
          git remote -v

      - name: Merge master (pre) → main (prod)
        run: |
          # Aseguramos que la rama 'main' exista antes de hacer checkout
          git fetch produccion
          if git show-ref --verify --quiet refs/remotes/produccion/main; then
            git checkout main
          else
            echo "La rama 'main' no existe en el repositorio de producción"
            exit 1
          fi
          git merge origin/master --no-edit || echo "Error al hacer merge"
          git push produccion main || echo "Error al hacer push"
